<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CityFunctionsTableSeeder extends Seeder
{
    public function run()
    {
        // Disable foreign key checks so we can truncate without the grid cells constraint blocking us
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('city_functions')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        DB::table('city_functions')->insert([
            [
                'name' => 'Police Station',
                'category' => 'Safety',
                'Safety' => 5,
                'Recreation' => 1,
                'Environment Quality' => 0,
                'Facilities' => 1,
                'Mobility' => 2,
                'image_path' => 'images/city_functions/police_station.png',
                'description' => 'A facility where police officers work and coordinate law enforcement operations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fire Station',
                'category' => 'Safety',
                'Safety' => 4,
                'Recreation' => 1,
                'Environment Quality' => 2,
                'Facilities' => 1,
                'Mobility' => 2,
                'image_path' => 'images/city_functions/fire_station.png',
                'description' => 'A building housing fire engines and the personnel who respond to fire emergencies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Park',
                'category' => 'Recreation',
                'Safety' => -2,
                'Recreation' => 5,
                'Environment Quality' => 4,
                'Facilities' => 0,
                'Mobility' => 0,
                'image_path' => 'images/city_functions/park.png',
                'description' => 'A green space for relaxation, outdoor activities, and family gatherings.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cinema',
                'category' => 'Recreation',
                'Safety' => -1,
                'Recreation' => 4,
                'Environment Quality' => 0,
                'Facilities' => 2,
                'Mobility'    => 0,
                'image_path' => 'images/city_functions/cinema.png',
                'description' => 'A place where movies are shown for the entertainment of the public.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sport Center',
                'category' => 'Recreation',
                'Safety' => 0,
                'Recreation' => 5,
                'Environment Quality' => 2,
                'Facilities' => 3,
                'Mobility'    => 0,
                'image_path' => 'images/city_functions/sport_center.png',
                'description' => 'A facility for sports and physical activities.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Water purification plant',
                'category' => 'Environment Quality',
                'Safety' => 0,
                'Recreation' => 0,
                'Environment Quality' => 5,
                'Facilities' => 2,
                'Mobility' => 0,
                'image_path' => 'images/city_functions/water_purification_plant.png',
                'description' => 'A facility for treating and purifying water for public use.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'School',
                'category' => 'Facilities',
                'Safety' => 2,
                'Recreation' => 2,
                'Environment Quality' => 0,
                'Facilities' => 5,
                'Mobility' => -3,
                'image_path' => 'images/city_functions/school.png',
                'description' => 'Institutions for formal learning and education.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shopping Mall',
                'category' => 'Facilities',
                'Safety' => 0,
                'Recreation' => 0,
                'Environment Quality' => -2,
                'Facilities' => 5,
                'Mobility' => 0,
                'image_path' => 'images/city_functions/shopping_mall.png',
                'description' => 'A commercial complex hosting multiple retail stores and services.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hospital',
                'category' => 'Facilities',
                'Safety' => 3,
                'Recreation' => 0,
                'Environment Quality' => 0,
                'Facilities' => 5,
                'Mobility' => 0,
                'image_path' => 'images/city_functions/hospital.png',
                'description' => 'A medical facility providing healthcare services to the community.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Station',
                'category' => 'Mobility',
                'Safety' => -2,
                'Recreation' => 2,
                'Environment Quality' => 0,
                'Facilities' => 4,
                'Mobility' => 5,
                'image_path' => 'images/city_functions/station.png',
                'description' => 'A transportation hub where vehicles stop to pick up or drop off passengers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Road',
                'category' => 'Mobility',
                'Safety' => -4,
                'Recreation' => 2,
                'Environment Quality' => -4,
                'Facilities' => 3,
                'Mobility' => 5,
                'image_path' => 'images/city_functions/road.png',
                'description' => 'A transportation hub where vehicles stop to pick up or drop off passengers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bicycle Lane',
                'category' => 'Mobility',
                'Safety' => 0,
                'Recreation' => 3,
                'Environment Quality' => 3,
                'Facilities' => 3,
                'Mobility' => 4,
                'image_path' => 'images/city_functions/bicycle_lane.png',
                'description' => 'A dedicated path for cyclists.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gas Station',
                'category' => 'Mobility',
                'Safety' => -2,
                'Recreation' => 0,
                'Environment Quality' => -4,
                'Facilities' => 1,
                'Mobility' => 4,
                'image_path' => 'images/city_functions/gas_station.png',
                'description' => 'A facility for refueling vehicles with fuel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}